name: Build Template
on:
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  build:
    name: ğŸ—ï¸ Build
    runs-on: ubuntu-latest
    env:
      TEMPLATE_PATH: "./src/templates/UmbracoPackageTemplate/src/UmbracoPackageTemplate.sln"
      PACKAGE_PATH: "./src/templates/UmbracoPackageTemplate/src/UmbracoPackageTemplate/UmbracoPackageTemplate.csproj"
      ARTIFACT_NAME: "jcdcdev-umbraco-package-template"
      ARTIFACT_OUTPUT: "./output"
      DOTNET_VERSION: "8.0.x"
      NPM_VERSION: "21.x"
      NPM_WORKING_DIR: "./src/templates/UmbracoPackageTemplate/src/UmbracoPackageTemplate.Client"
    steps:
    - uses: actions/checkout@v4
      name: ğŸ“¥ Checkout repository
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NPM_VERSION }}
    - name: ğŸ—ï¸ Build JavaScript
      run: |
        pushd ${{ env.NPM_WORKING_DIR }}
        npm install
        npm run build
        popd
    - name: ğŸ› ï¸ Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: â¬ Restore dependencies
      run: dotnet restore ${{ env.TEMPLATE_PATH }}
    - name: ğŸ—ï¸ Build .NET
      run: dotnet build ${{ env.TEMPLATE_PATH }}
    - name: ğŸ—ï¸ Build NuGet Package
      run: dotnet pack ${{ env.PACKAGE_PATH }} --output ${{ env.ARTIFACT_OUTPUT }}
    - name: â¬†ï¸ Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_OUTPUT }}